#服务注册中心配置
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9081/eureka/
  instance:
    appname: cloud-service

server:
  port: 9072

spring:
  application:
    name: cloud-service


