server:
  port: 9082
  
#服务注册中心配置
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:9081/eureka/
spring:
  application:
    name: spring-cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/zzj0222/SpringCloudProject/     # 配置git仓库的地址
          search-paths: laiai-spring-cloud-microservice                             # git仓库地址下的相对地址，可以配置多个，用,分割。
          username:                                              # git仓库的账号
          password:    